# pygame.font.init()
        # title = pygame.font.Font('freesansbold.ttf', 32)
        # title_text = title.render("The Last Of You 2",True,(255, 0, 0))
        # textRect = title_text.get_rect()
        # textRect.center = (1920/2,50)
        # screen.blit(title_text, textRect)